# Generated by Django 2.2.3 on 2019-12-02 11:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Block',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1)),
                ('no_of_block', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Hostel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100)),
                ('gender', models.CharField(choices=[('N', 'None'), ('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('no_of_block', models.IntegerField()),
                ('warden', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no', models.CharField(max_length=3)),
                ('condition', models.CharField(choices=[('G', 'Good'), ('B', 'Bad'), ('T', 'Terrible')], max_length=1)),
                ('block', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='hms.Block')),
                ('hostel', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='hms.Hostel')),
            ],
        ),
        migrations.AddField(
            model_name='block',
            name='hostel',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='hms.Hostel'),
        ),
    ]
