# Generated by Django 2.2.3 on 2019-12-02 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hms', '0003_auto_20191202_1210'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='block',
            name='no_of_block',
        ),
    ]
