# Generated by Django 2.2.3 on 2019-12-02 13:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hms', '0004_remove_block_no_of_block'),
    ]

    operations = [
        migrations.CreateModel(
            name='Warden',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Your Full name', max_length=100)),
                ('staff_id', models.CharField(max_length=50)),
                ('gender', models.CharField(choices=[('N', 'None'), ('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('user', models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
